export const CMS_ROUTES = {
  dashboard: "cms",
  library: "cms/library",
  upload: "cms/upload",
  vodMovies: "cms/vod/movies",
  vodMoviesNew: "cms/vod/movies/new",
  vodMoviesEdit: "cms/vod/movies/:id/edit",
  vodSeries: "cms/vod/series",
  vodSeriesNew: "cms/vod/series/new",
  vodSeriesEdit: "cms/vod/series/:id/edit",
  vodPlays: "cms/vod/plays",
  vodPlaysNew: "cms/vod/plays/new",
  vodPlaysEdit: "cms/vod/plays/:id/edit",
  vodGenres: "cms/vod/genres",
  vodGenresNew: "cms/vod/genres/new",
  vodGenresEdit: "cms/vod/genres/:id/edit",
  vodTvShows: "cms/vod/tv-shows",
  vodTvShowsNew: "cms/vod/tv-shows/new",
  vodTvShowsEdit: "cms/vod/tv-shows/:id/edit",
  musicSingers: "cms/music/singers",
  musicSingersNew: "cms/music/singers/new",
  musicSingersEdit: "cms/music/singers/:id/edit",
  musicSongs: "cms/music/songs",
  musicSongsNew: "cms/music/songs/new",
  musicSongsEdit: "cms/music/songs/:id/edit",
  musicGenres: "cms/music/genres",
  musicGenresNew: "cms/music/genres/new",
  musicGenresEdit: "cms/music/genres/:id/edit",
  streamingRadio: "cms/streaming/radio",
  streamingRadioNew: "cms/streaming/radio/new",
  streamingRadioEdit: "cms/streaming/radio/:id/edit",
  streamingChannels: "cms/streaming/channels",
  streamingChannelsNew: "cms/streaming/channels/new",
  streamingChannelsEdit: "cms/streaming/channels/:id/edit",
  streamingGenres: "cms/streaming/genres",
  streamingGenresNew: "cms/streaming/genres/new",
  streamingGenresEdit: "cms/streaming/genres/:id/edit",
  ads: "cms/ads",
  adsNew: "cms/ads/new",
  adsEdit: "cms/ads/:id/edit",
} as const;

export function cmsPath(
  route: (typeof CMS_ROUTES)[keyof typeof CMS_ROUTES],
): string {
  return `/${route}`;
}
